### PR TITLE
Check array/number bounds

### PR DESCRIPTION
**Pull request by ganymedes01**
depends on https://github.com/smartlyio/oats-runtime/pull/122

### CODE REVIEW

**Comment by sakari** [comment]
would be nice to have these constraints also in the runtime typeN structures.

**Comment by ganymedes01** [comment]
Do you mean like this?

```yml
    hahaha:
      type: number
      minimum: 10
      maximum: 40

```
```ts
export const makeHahaha: oar.make.Maker<ShapeOfHahaha, Hahaha> = oar.make.createMaker(function () { return oar.make.makeNumber(10, 40); });
```

**Comment by sakari** [comment]
like filling in these structures https://github.com/smartlyio/oats-runtime/blob/master/src/reflection-type.ts#L71

**Comment by ganymedes01** [comment]
oh right! got it 👍

**Comment by ganymedes01** [comment]
Done:
```ts
Object.assign(typeHahaha, {
    name: "Hahaha",
    definition: {
        type: "integer",
        minimum: 10,
        maximum: 40
    },
    maker: makeHahaha,
    isA: null
})
Object.assign(typeHehehe, {
    name: "Hehehe",
    definition: {
        type: "array",
        items: {
            type: "string"
        },
        minItems: 10,
        maxItems: 40
    },
    maker: makeHehehe,
    isA: null
})
```

**Comment by sakari** [comment]
did you add those to the type in oats-runtime?

**Comment by ganymedes01** [comment]
Now I did 😬
https://github.com/smartlyio/oats-runtime/pull/123

**Review by sakari — APPROVED** [review]
if this works with oats-runtime then looks a-ok

**Pull request merged**
